### ISSUE TITLE
Is nested CSS syntax highlighting not currently supported?

### ISSUE THREAD

**Issue by you-hengh** [fisheva/Eva-Theme#134]
### Screenshot

![Image](https://github.com/user-attachments/assets/5546e107-fc40-403e-98ac-268a146ad5d4)

### Code Snippet

```css
.keys {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;

  .key {
    border: 4px solid black;
    border-radius: 5px;
    margin: 1rem;
    font-size: 1.5rem;
    padding: 1rem 0.5rem;
    transition: all 0.07s;
    width: 100px;
    text-align: center;
    color: white;
    background: rgba(0, 0, 0, 0.4);
    text-shadow: 0 0 5px black;

    kbd {
      display: block;
      font-size: 40px;
    }
  }
}
```

## Notes

null
